services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: always
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always